let suggestions = [
  "mercury",
  "venus",
  "earth",
  "mars",
  "jupiter",
  "saturn",
  "uranus",
  "neptune",
  "sun",
  "mooon",
  "small launch vehicle",
  "aryabhata",
  "ceres",
  "eris",
  "gps-iir-1",
  "sputnik-1",
  "international space station",
  "rosat",
  "voyager1",
  "voyager2",
  "gslv",
  "vesta",
  "mars natural satellites",
  "jupiter natural satellites",
  "saturn natural satellites",
  "uranus natural satellites",
  "neptune natural satellites",
  "halley's comet",
  "hale-bopp",
  "tempel-tuttel",
  "mars reconnaissance orbiter",
  "hubble space telescope",
  "hygiea",
  "pallas",
  "rosat",
  "Saturn V",
  "SpaceX Falcon Heavy"
];